// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "monthly", Type: field.TypeFloat64, Default: 0},
		{Name: "weekly", Type: field.TypeFloat64, Default: 0},
		{Name: "colour", Type: field.TypeString},
		{Name: "type", Type: field.TypeString, Default: "expense"},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "time", Type: field.TypeInt64},
		{Name: "description", Type: field.TypeString},
		{Name: "amount", Type: field.TypeFloat64, Default: 0},
		{Name: "ignored", Type: field.TypeBool, Default: false},
		{Name: "category_id", Type: field.TypeInt, Nullable: true},
		{Name: "reimbursed_by_id", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transactions_categories_transactions",
				Columns:    []*schema.Column{TransactionsColumns[5]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "transactions_transactions_reimbursed_by_transaction",
				Columns:    []*schema.Column{TransactionsColumns[6]},
				RefColumns: []*schema.Column{TransactionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CategoriesTable,
		TransactionsTable,
	}
)

func init() {
	TransactionsTable.ForeignKeys[0].RefTable = CategoriesTable
	TransactionsTable.ForeignKeys[1].RefTable = TransactionsTable
}
