// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ent} from '../models';

export function Close():Promise<void>;

export function CreateCategory(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string):Promise<ent.Category>;

export function CreateTransaction(arg1:number,arg2:string,arg3:number,arg4:number,arg5:boolean):Promise<ent.Transaction>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function GetCategories():Promise<Array<ent.Category>>;

export function GetCategoriesByType(arg1:string):Promise<Array<ent.Category>>;

export function GetCategoryByID(arg1:number):Promise<ent.Category>;

export function GetCategoryByName(arg1:string):Promise<ent.Category>;

export function GetCategoryTransactions(arg1:ent.Category):Promise<Array<ent.Transaction>>;

export function GetTransactionByID(arg1:number):Promise<ent.Transaction>;

export function GetTransactions():Promise<Array<ent.Transaction>>;

export function GetTransactionsExpense():Promise<Array<ent.Transaction>>;

export function GetTransactionsIncome():Promise<Array<ent.Transaction>>;

export function Open():Promise<void>;

export function UpdateCategory(arg1:number,arg2:any,arg3:any,arg4:any,arg5:any,arg6:any):Promise<ent.Category>;

export function UpdateTransaction(arg1:number,arg2:any,arg3:any,arg4:any,arg5:any,arg6:any,arg7:any):Promise<ent.Transaction>;
