// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function Close():Promise<void>;

export function Exec(arg1:string,arg2:Array<any>):Promise<void>;

export function Open():Promise<void>;

export function Ping():Promise<void>;

export function QueryCategories(arg1:string,arg2:Array<any>):Promise<Array<db.Category>>;

export function QueryRowCategory(arg1:string,arg2:Array<any>):Promise<db.Category>;

export function QueryRowCount(arg1:string,arg2:Array<any>):Promise<number>;

export function QueryTransaction(arg1:string,arg2:Array<any>):Promise<db.Transaction>;

export function QueryTransactions(arg1:string,arg2:Array<any>):Promise<Array<db.Transaction>>;
