// Code generated by ent, DO NOT EDIT.

package category

import (
	"go-budget/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Category {
	return predicate.Category(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Category {
	return predicate.Category(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Category {
	return predicate.Category(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Category {
	return predicate.Category(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Category {
	return predicate.Category(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Category {
	return predicate.Category(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Category {
	return predicate.Category(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldName, v))
}

// Monthly applies equality check predicate on the "monthly" field. It's identical to MonthlyEQ.
func Monthly(v float64) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldMonthly, v))
}

// Weekly applies equality check predicate on the "weekly" field. It's identical to WeeklyEQ.
func Weekly(v float64) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldWeekly, v))
}

// Colour applies equality check predicate on the "colour" field. It's identical to ColourEQ.
func Colour(v string) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldColour, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldType, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Category {
	return predicate.Category(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Category {
	return predicate.Category(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Category {
	return predicate.Category(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Category {
	return predicate.Category(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Category {
	return predicate.Category(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Category {
	return predicate.Category(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Category {
	return predicate.Category(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Category {
	return predicate.Category(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Category {
	return predicate.Category(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Category {
	return predicate.Category(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Category {
	return predicate.Category(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Category {
	return predicate.Category(sql.FieldContainsFold(FieldName, v))
}

// MonthlyEQ applies the EQ predicate on the "monthly" field.
func MonthlyEQ(v float64) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldMonthly, v))
}

// MonthlyNEQ applies the NEQ predicate on the "monthly" field.
func MonthlyNEQ(v float64) predicate.Category {
	return predicate.Category(sql.FieldNEQ(FieldMonthly, v))
}

// MonthlyIn applies the In predicate on the "monthly" field.
func MonthlyIn(vs ...float64) predicate.Category {
	return predicate.Category(sql.FieldIn(FieldMonthly, vs...))
}

// MonthlyNotIn applies the NotIn predicate on the "monthly" field.
func MonthlyNotIn(vs ...float64) predicate.Category {
	return predicate.Category(sql.FieldNotIn(FieldMonthly, vs...))
}

// MonthlyGT applies the GT predicate on the "monthly" field.
func MonthlyGT(v float64) predicate.Category {
	return predicate.Category(sql.FieldGT(FieldMonthly, v))
}

// MonthlyGTE applies the GTE predicate on the "monthly" field.
func MonthlyGTE(v float64) predicate.Category {
	return predicate.Category(sql.FieldGTE(FieldMonthly, v))
}

// MonthlyLT applies the LT predicate on the "monthly" field.
func MonthlyLT(v float64) predicate.Category {
	return predicate.Category(sql.FieldLT(FieldMonthly, v))
}

// MonthlyLTE applies the LTE predicate on the "monthly" field.
func MonthlyLTE(v float64) predicate.Category {
	return predicate.Category(sql.FieldLTE(FieldMonthly, v))
}

// WeeklyEQ applies the EQ predicate on the "weekly" field.
func WeeklyEQ(v float64) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldWeekly, v))
}

// WeeklyNEQ applies the NEQ predicate on the "weekly" field.
func WeeklyNEQ(v float64) predicate.Category {
	return predicate.Category(sql.FieldNEQ(FieldWeekly, v))
}

// WeeklyIn applies the In predicate on the "weekly" field.
func WeeklyIn(vs ...float64) predicate.Category {
	return predicate.Category(sql.FieldIn(FieldWeekly, vs...))
}

// WeeklyNotIn applies the NotIn predicate on the "weekly" field.
func WeeklyNotIn(vs ...float64) predicate.Category {
	return predicate.Category(sql.FieldNotIn(FieldWeekly, vs...))
}

// WeeklyGT applies the GT predicate on the "weekly" field.
func WeeklyGT(v float64) predicate.Category {
	return predicate.Category(sql.FieldGT(FieldWeekly, v))
}

// WeeklyGTE applies the GTE predicate on the "weekly" field.
func WeeklyGTE(v float64) predicate.Category {
	return predicate.Category(sql.FieldGTE(FieldWeekly, v))
}

// WeeklyLT applies the LT predicate on the "weekly" field.
func WeeklyLT(v float64) predicate.Category {
	return predicate.Category(sql.FieldLT(FieldWeekly, v))
}

// WeeklyLTE applies the LTE predicate on the "weekly" field.
func WeeklyLTE(v float64) predicate.Category {
	return predicate.Category(sql.FieldLTE(FieldWeekly, v))
}

// ColourEQ applies the EQ predicate on the "colour" field.
func ColourEQ(v string) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldColour, v))
}

// ColourNEQ applies the NEQ predicate on the "colour" field.
func ColourNEQ(v string) predicate.Category {
	return predicate.Category(sql.FieldNEQ(FieldColour, v))
}

// ColourIn applies the In predicate on the "colour" field.
func ColourIn(vs ...string) predicate.Category {
	return predicate.Category(sql.FieldIn(FieldColour, vs...))
}

// ColourNotIn applies the NotIn predicate on the "colour" field.
func ColourNotIn(vs ...string) predicate.Category {
	return predicate.Category(sql.FieldNotIn(FieldColour, vs...))
}

// ColourGT applies the GT predicate on the "colour" field.
func ColourGT(v string) predicate.Category {
	return predicate.Category(sql.FieldGT(FieldColour, v))
}

// ColourGTE applies the GTE predicate on the "colour" field.
func ColourGTE(v string) predicate.Category {
	return predicate.Category(sql.FieldGTE(FieldColour, v))
}

// ColourLT applies the LT predicate on the "colour" field.
func ColourLT(v string) predicate.Category {
	return predicate.Category(sql.FieldLT(FieldColour, v))
}

// ColourLTE applies the LTE predicate on the "colour" field.
func ColourLTE(v string) predicate.Category {
	return predicate.Category(sql.FieldLTE(FieldColour, v))
}

// ColourContains applies the Contains predicate on the "colour" field.
func ColourContains(v string) predicate.Category {
	return predicate.Category(sql.FieldContains(FieldColour, v))
}

// ColourHasPrefix applies the HasPrefix predicate on the "colour" field.
func ColourHasPrefix(v string) predicate.Category {
	return predicate.Category(sql.FieldHasPrefix(FieldColour, v))
}

// ColourHasSuffix applies the HasSuffix predicate on the "colour" field.
func ColourHasSuffix(v string) predicate.Category {
	return predicate.Category(sql.FieldHasSuffix(FieldColour, v))
}

// ColourEqualFold applies the EqualFold predicate on the "colour" field.
func ColourEqualFold(v string) predicate.Category {
	return predicate.Category(sql.FieldEqualFold(FieldColour, v))
}

// ColourContainsFold applies the ContainsFold predicate on the "colour" field.
func ColourContainsFold(v string) predicate.Category {
	return predicate.Category(sql.FieldContainsFold(FieldColour, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Category {
	return predicate.Category(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Category {
	return predicate.Category(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Category {
	return predicate.Category(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Category {
	return predicate.Category(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Category {
	return predicate.Category(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Category {
	return predicate.Category(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Category {
	return predicate.Category(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Category {
	return predicate.Category(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Category {
	return predicate.Category(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Category {
	return predicate.Category(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Category {
	return predicate.Category(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Category {
	return predicate.Category(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Category {
	return predicate.Category(sql.FieldContainsFold(FieldType, v))
}

// HasTransactions applies the HasEdge predicate on the "transactions" edge.
func HasTransactions() predicate.Category {
	return predicate.Category(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TransactionsTable, TransactionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransactionsWith applies the HasEdge predicate on the "transactions" edge with a given conditions (other predicates).
func HasTransactionsWith(preds ...predicate.Transaction) predicate.Category {
	return predicate.Category(func(s *sql.Selector) {
		step := newTransactionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Category) predicate.Category {
	return predicate.Category(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Category) predicate.Category {
	return predicate.Category(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Category) predicate.Category {
	return predicate.Category(sql.NotPredicates(p))
}
