// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Categorize(arg1, arg2, arg3) {
  return window['go']['main']['App']['Categorize'](arg1, arg2, arg3);
}

export function LoadFile(arg1, arg2) {
  return window['go']['main']['App']['LoadFile'](arg1, arg2);
}
