// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {db} from '../models';

export function Categorize(arg1:context.Context,arg2:db.Db,arg3:Array<db.Transaction>):Promise<Array<db.Transaction>>;

export function CategorizeUncategorized(arg1:context.Context,arg2:db.Db):Promise<void>;

export function LoadFile(arg1:context.Context,arg2:db.Db):Promise<void>;
