// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {db} from '../models';

export function LoadFile(arg1:context.Context,arg2:db.Db):Promise<void>;
