// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sql} from '../models';

export function Close():Promise<void>;

export function Exec(arg1:string,arg2:Array<any>):Promise<sql.Result>;

export function Open():Promise<void>;

export function Ping():Promise<void>;

export function Query(arg1:string,arg2:Array<any>):Promise<Array<any>>;

export function QueryRow(arg1:string,arg2:Array<any>):Promise<any>;
