name: Go Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: dAppServer/wails-build-action@main
        with:
          build-name: go-budget
          build-platform: linux/amd64
          package: true
          go-version: '1.24'
      - name: Test
        run: go test ./...